### ISSUE TITLE
People are getting Game state timeout.

### ISSUE THREAD

**Issue by jakjus** [mertushka/haxball.js#10]
People are getting Game state timeout when connecting.

From server perspective it looks like this:
```
"<player> has joined."
<player has 0 ping for 2 seconds>
"<player> has left."
```

Specs:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

I'll try ubuntu later

**Comment by jakjus** [comment]
Ok I discovered the issue - it has nothing with connection type.

Players disconnect when there are **9 players on the server currently**.

So there has to be some unknown limitation that allows only 9 players to be connected through webrtc or something.

**Comment by jakjus** [comment]
I can confirm the issue happening also on my local MacOS M1 chip.

**Comment by mertushka** [comment]
Tested on Windows 10 with >9 people and there was no connection problem. I copied Usage Example Code on README.md and didn't change anything. Maybe there is something with your own code that corrupts the connection. Are you sure you've stably adapted the JavaScript code to NodeJS?

**Comment by jakjus** [comment]
I confirm that test code runs fine. So it is indeed something about the code that I'll try to debug...

**Comment by jakjus** [comment]
Okay, it only happens when `Winky's Challenge` map is launched.

**Comment by jakjus** [comment]
It works after I've removed some random parts from the map. 

The issue therefore is probably with map having too many objects. Interesting! I'll make a full solution later today and close this.

**Comment by mertushka** [comment]
> It works after I've removed some random parts from the map.
> 
> The issue therefore is probably with map having too many objects. Interesting! I'll make a full solution later today and close this.

Glad you got it fixed, really interesting by the way...

**Comment by jakjus** [comment]
It was due to having **too many Discs**, to be precise. I have deleted unnecessary discs from the map.

It's worth to note that script adds `c1` cGroup to every joining player. Maybe there were too many discs with `c1` cGroup after few players joined.

Snippet:
```
// src/utils.ts

let cf = room.CollisionFlags
let props = room.getPlayerDiscProperties(p.id)
room.setPlayerDiscProperties(p.id, {...props, cGroup: cf.c1})
```

Solved.
