### ISSUE TITLE
File is not defined

### ISSUE THREAD

**Issue by byoxygen** [mertushka/haxball.js#12]
**_Hi bro, can you solve this problem?_** 

```
form.append(null, new File([room.stopRecording()], `HBReplay-${RecSistem.getCustomDate()}.hbr2`, { type: "text/plain" }));
                                  ^
ReferenceError: File is not defined
```

**_I added var File = require('fs'); after then but says;_** 

```
form.append(null, new File([room.stopRecording()], `HBReplay-${RecSistem.getCustomDate()}.hbr2`, { type: "text/plain" }));
                             
TypeError: File is not a constructor
```

**Comment by mertushka** [comment]
Learn NodeJS

**Comment by byoxygen** [comment]
> Learn NodeJS

What is the solution to my problem? 

Please tell me how should I do it.

**Comment by byoxygen** [comment]
@mertushka Maybe related to your used browser? Please find a solution.

**Comment by mertushka** [comment]
> @mertushka Maybe related to your used browser? Please find a solution.

Find a solution yourself. You can't achieve anything in life without effort. Just do research in the "right" way, not just copy and pasting. If you bother me again, I will delete this issue.

**Comment by byoxygen** [comment]
Why you are so prejudiced, i have tried many things except copy paste. 
Do have to be a developer to solve this problem? I asked you because you are a developer of this script.
