### ISSUE TITLE
App console looks like real time console

### ISSUE THREAD

**Issue by furkanardagul** [mertushka/haxball.js#16]
Hello, can we receive data from an input in the application running on the operating system console and send it to the game console?

Actually, what I really want is for the system console to work just like the Google Chrome console.

**Comment by mertushka** [comment]
The example below can solve your issue:
```js
process.stdout.write("> ");

process.stdin.on("data", (data) => {
  const input = data.toString();
  try {
    const evalResult = eval(input);
    console.log(evalResult);
  } catch (err) {
    console.log("eval error:", err);
  }
  process.stdout.write("> ");
});
```

You can access variables and evaluate codes in console like `<RoomObject>.sendAnnouncement("hi")` and etc..

**Comment by furkanardagul** [comment]
In addition, in some cases, I get the error localStorage is not defined as a structure.

Code:
```js
      const storage = localStorage.getItem('xxx');
      if (storage == null) {
        localStorage.setItem('xxx', '[]');
      }
```
Response:
```bash
ReferenceError: localStorage is not defined
```

**Comment by mertushka** [comment]
NodeJS and Browser Javascript are different things. NodeJS does not include browser specific things like Window, localStorage, indexedDB etc. Therefore, you should produce your own solutions, or search for the relevant module via NPM.

Example:
https://www.npmjs.com/package/node-localstorage
```js
if (typeof localStorage === "undefined" || localStorage === null) {
  var LocalStorage = require('node-localstorage').LocalStorage;
  localStorage = new LocalStorage('./scratch');
}
```
*I was able to reach this result with a very simple google search: NodeJS localStorage*

I strongly recommend you to learn NodeJS, none of the above issues are related to the haxball.js module, but they can be easily understood and solved with intermediate NodeJS knowledge.
