### ISSUE TITLE
GetPlayerList returning Promise

### ISSUE THREAD

**Issue by ImmersHaxball** [mertushka/haxball.js#2]
Hey,

First of all thanks for this package! I used to use _haxball-server-nodejs_ which just simply made it possible to run my room on NodeJS but sadly they stopped developing their package and it sometimes causes my rooms to crash. So now I'm trying this one, but I'm not sure I understand it all correctly. Excuse my possible bad understanding of it, but I'm not a native js developer ^^

So I tried to convert my code to the way your package works, which means instead of 
`room.onPlayerChat = function(player, message) {
blabla
}`
I now have
`room.on("onPlayerChat", = function(player, message) {
blabla
});`

That all seems to work fine.
But in my old code I used to loop over the players like this:
`players = room.getPlayerList();`
`for(let player of players) {
blabla
}`
But I'm not sure how to do that with your package. Tried some things but I think the problem is it returns a Promise? Does this mean this simple loop is no longer possible? Hope I'm missing something!

Thanks in advance,
Immers

**Comment by mertushka** [comment]
You need to use `await room.getPlayerList();` to make Promise resolved. Because all methods are Promise based.

**Comment by ImmersHaxball** [comment]
Thanks! That worked indeed.
One more quick question. If I want to make a player admin I used to be able to do:
`room.setPlayerAdmin(playerid, true)`
Now I noticed in your code you don't have this anymore, but you create a Player object.
How do I use a Player object in my code?
Because obviously when I do
`player = await room.getPlayer(playerid);`
`player.setAdmin(true);`
I get an error saying player.setAdmin() is not a function, as my player is not a Player object.

**Comment by ImmersHaxball** [comment]
Oh great thanks! Didn't see the example, maybe it's an idea to put it somewhere on the project page here.
Thanks a lot for your quick help!

**Comment by mertushka** [comment]
Glad I could help. I don't have time to update the project but I think it will not be a problem since it is stable. You can ask questions in any problem.

- Cheers, mertushka.

**Comment by mertushka** [comment]
With release of haxball.js@2.0.0 this issue is deprecated.
