### ISSUE TITLE
error when trying to up the room

### ISSUE THREAD

**Issue by MoisesAsafi** [mertushka/haxball.js#20]
\node_modules\node-fetch\lib\index.js:273
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://www.haxball.com/rs/api/host reason: Unexpected token < in JSON at position 0
    at C:\Users\moises\Documents\mxm\node_modules\node-fetch\lib\index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\moises\Documents\mxm\node_modules\haxball.js\src\index.js:1877:26 {
  type: 'invalid-json'
}

**Comment by peppewarrior1** [comment]
same problem. There was a DDOS attack this morning

**Comment by AndreaCasaluci** [comment]
Same problem here, I don't think it's a HaxballJS problem though

**Comment by mertushka** [comment]
The problem is either on Cloudflare or the Haxball servers, not on haxball.js side.

@basro Is Cloudflare does maintenance or you doing something in the backend?
