### ISSUE TITLE
Can't create a room with proxy

### ISSUE THREAD

**Issue by hacibartu922** [mertushka/haxball.js#22]
Hi, I'm trying to create a room with a private proxy but I'm failing, here is my code and the error:

```js
var room = HBInit({
    roomName: 'Test Room',
    maxPlayers: 16,
    debug: true,
    proxy: 'http://209.99.129.239:6227:login:password'
});
```

I get the following error: 

```
Error: connect ECONNREFUSED 209.99.129.239:80
```

The port I specified (6227) is not the same as the port in the error message (80), what should I do?

**Comment by mertushka** [comment]
The correct formation is `http://login:password@209.99.129.239:6227`.
