### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by MoisesAsafi** [mertushka/haxball.js#24]
Is there any way for the Invalid Token Error to terminate the client but not all of my code?

Type this error:
![image](https://github.com/mertushka/haxball.js/assets/68512914/58732a6a-1e3c-462f-b58a-b4183dd50e13)

It finishes the client but not my code.

**Comment by jakjus** [comment]
Put the HBInit function in the `try/catch` OR add a `.catch()` depending on if you use await/async syntax.

With `await/async`:
```js
const HBInit = await HaxballJS
try {
  const room = HBInit({
    roomName: 'test',
    token: 'thr1.AAAAAGUoFkn6N1TdUatJBg.bS6fQZYprgM'
  })
} catch (e) {
  console.error(e)
}
```

Without async/await:
```js
HaxballJS.then((HBInit) => {
  const room = HBInit({
    roomName: "Haxball.JS",
    maxPlayers: 16,
    public: true,
    noPlayer: true,
    token: "YOUR_TOKEN_HERE", // Required
  })
}).catch(e => console.error(e));
```

**Comment by mertushka** [comment]
After the new release `2.1.3`, the `try/catch` block won't work on `HBInit` function because i can't make `throw "Invalid Token Error"` on @basro's new error mechanism. Instead, console errors will appear without a `throw`.
