### ISSUE TITLE
New Event/Function Added

### ISSUE THREAD

**Issue by AndreaCasaluci** [mertushka/haxball.js#26]
Hello,
Basro has included a new function in the Headless API, namely the onTeamsLockChange function I suggested.
I tried to use it in my script in haxball.js but it doesn't work, while with the code directly launched in the browser console it works, so I guess there needs to be a little update on that for haxball.js too.

@mertushka

**Comment by jakjus** [comment]
I confirm there is an update in headless.min.js - one of source files of haxball.com/headless - with tag "b8aba8f2", that is not yet included in haxball.js.

@mertushka  will probably take care of the changes, but if he does not reply, I'll do it. The development time will depend on how much the source code has been changed.

**Comment by mertushka** [comment]
`onTeamsLockChange` event is included in new release `2.1.3`.
