### ISSUE TITLE
getAddrInfo

### ISSUE THREAD

**Issue by furkanardagul** [mertushka/haxball.js#27]
Hi,

I had opened a topic before, but since I was on break, I couldn't respond clearly. I opened a topic again in the attachment. After a while, the rooms I open with the module give the attached error and explode.

https://github.com/haxball/haxball-issues/issues/2091

**Comment by mertushka** [comment]
@furkanardagul The latest release of haxball.js (`v2.1.3`) is no longer using `node-fetch` module. Are you sure that bug still appears in latest release?

**Comment by furkanardagul** [comment]
I will update again and report back. I was getting this error when I was on version 2.1.2.

**Comment by mertushka** [comment]
@furkanardagul Due to the time that has passed, i am marking this issue as solved.
