### ISSUE TITLE
how to add variables and functions in node in the terminal

### ISSUE THREAD

**Issue by Gimenez20** [mertushka/haxball.js#30]
Hi, i wanted to know if is possible to add something about to edit variables or functions when the room is opened, without close the room always. On the headless host website is possible to do it @mertushka

**Comment by Gimenez20** [comment]
so? @mertushka

**Comment by mertushka** [comment]
@Gimenez20 I assume that code evalution in NodeJS environment is what you asking about so that might be helpful https://github.com/mertushka/haxball.js/issues/16#issuecomment-1425159848 _(sorry for late response)_
