### ISSUE TITLE
Room Closing Socket randomly

### ISSUE THREAD

**Issue by Imazinho** [mertushka/haxball.js#35]
My rooms are often **closing** the connection without any error or anything like that, I use catch in all events so clearly it's some problem with **haxballjs**

**Comment by mertushka** [comment]
How can we reproduce the issue? Could you share your script along with details about your platform and Node.js version?

**Comment by Imazinho** [comment]
Currently I use several scripts with different structures and both of them have this problem, nodejs versions: **20.18.0** and **22.11.0**. Yesterday I managed to get the following error in one of the rooms: 

node:internal/process/promises:394
triggerUncaughtException(err, true /* fromPromise */);
^

[Error: Failed to set ICE candidate; RTCPeerConnection is closed.]

**Comment by mertushka** [comment]
Please use Node.js 18.x and provide feedback. I can't offer an exact solution as I am unable to reproduce the issue.

**Comment by Imazinho** [comment]
Okay, I'll test it, I received another error in one of the rooms: 
/root/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError('request to ${request.url} failed, reason: ${err.message}', 'system', err));
                               ^
FetchError: request to https://www.haxball.com/rs/api/host failed, reason: Client network socket disconnected before secure TLS connection was established
    at ClientRequest. <anonymous> (/root/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}

Node.js v20.18.0

**Comment by mertushka** [comment]
Which `haxball.js` version are you running? It's strange because I'm not using the node-fetch module.

**Comment by Imazinho** [comment]
I'm using 2.1.2, I downgraded thinking I would solve the problem but I was unsuccessful

**Comment by mertushka** [comment]
Please use the latest haxball.js release with Node.JS 18.x

**Comment by mertushka** [comment]
I have no idea why it's restarts by itself.
