### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by FedericoBarberon** [mertushka/haxball.js#8]
Every time I start a server and want to get in I get the following error:

**Connection Failed**

**Failed to connect to room host.**
**If this problem persists please see the [troubleshooting guide](https://github.com/haxball/haxball-issues/wiki/Connection-Issues).**

**Comment by mertushka** [comment]
It's most likely a problem with the internet provider you opened the room with. Where are you hosting the room?

**Comment by FedericoBarberon** [comment]
im using Gitpod, its an online IDE

**Comment by mertushka** [comment]
> im using Gitpod, its an online IDE

The problem may be related to the restrictions Gitpod imposes. You can use Heroku instead of Gitpod.

**Comment by FedericoBarberon** [comment]
Ok, ill try that. Thank you!

**Comment by mertushka** [comment]
No problem. Let me know if your issue is solved.

**Comment by FedericoBarberon** [comment]
Yeah! It works. Ty :)
